### ISSUE TITLE
Add basic e2e tests

### ISSUE THREAD

**Issue by bennyz** [qarax/qarax#77]
Installing a host and starting a VM should be good enough for now

**Comment by douek** [comment]
contrib scripts - can use does to create machine
using py test 
The script will run from the manager machine.
the steps are :
creating a host
ping host
add a host to qarax
install qarax on host
healthcheck
shh to host and check
download drive and kernel from firecracker to the manager machine
create storage(db)
create drive(db)
create kernel(db)
create rootfs on host with the ids (storage is just storage)
copy the drive and kernel to manager machine
add VM to the created host with kernel and storage
start vm
ssh the vm
stop vm 
check that the process end

**Comment by bennyz** [comment]
As part of the axum/sqlx rewrite, some has been implemented in https://github.com/qarax/qarax/blob/master/e2e/e2e.py
Work should continue there
